/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNamespacesRouteRouteImport } from './routes/_authenticated/namespaces/route'
import { Route as AuthenticatedConnectionsRouteRouteImport } from './routes/_authenticated/connections/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedNamespacesIndexRouteImport } from './routes/_authenticated/namespaces/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedConnectionsIndexRouteImport } from './routes/_authenticated/connections/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedNamespacesSplatRouteImport } from './routes/_authenticated/namespaces/$'
import { Route as AuthenticatedConnectionsConnectionIdRouteImport } from './routes/_authenticated/connections/$connectionId'
import { Route as AuthenticatedAdminUsersRouteRouteImport } from './routes/_authenticated/admin/users/route'
import { Route as AuthenticatedAdminGroupsRouteRouteImport } from './routes/_authenticated/admin/groups/route'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminGroupsIndexRouteImport } from './routes/_authenticated/admin/groups/index'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users/$userId'
import { Route as AuthenticatedAdminGroupsGroupIdRouteImport } from './routes/_authenticated/admin/groups/$groupId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNamespacesRouteRoute =
  AuthenticatedNamespacesRouteRouteImport.update({
    id: '/namespaces',
    path: '/namespaces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRouteRoute =
  AuthenticatedConnectionsRouteRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNamespacesIndexRoute =
  AuthenticatedNamespacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNamespacesRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsIndexRoute =
  AuthenticatedConnectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConnectionsRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedNamespacesSplatRoute =
  AuthenticatedNamespacesSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedNamespacesRouteRoute,
  } as any)
const AuthenticatedConnectionsConnectionIdRoute =
  AuthenticatedConnectionsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => AuthenticatedConnectionsRouteRoute,
  } as any)
const AuthenticatedAdminUsersRouteRoute =
  AuthenticatedAdminUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGroupsRouteRoute =
  AuthenticatedAdminGroupsRouteRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersRouteRoute,
  } as any)
const AuthenticatedAdminGroupsIndexRoute =
  AuthenticatedAdminGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminGroupsRouteRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRouteRoute,
  } as any)
const AuthenticatedAdminGroupsGroupIdRoute =
  AuthenticatedAdminGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedAdminGroupsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/connections': typeof AuthenticatedConnectionsRouteRouteWithChildren
  '/namespaces': typeof AuthenticatedNamespacesRouteRouteWithChildren
  '/admin/groups': typeof AuthenticatedAdminGroupsRouteRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteRouteWithChildren
  '/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/namespaces/': typeof AuthenticatedNamespacesIndexRoute
  '/admin/groups/$groupId': typeof AuthenticatedAdminGroupsGroupIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/connections': typeof AuthenticatedConnectionsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/namespaces': typeof AuthenticatedNamespacesIndexRoute
  '/admin/groups/$groupId': typeof AuthenticatedAdminGroupsGroupIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/connections': typeof AuthenticatedConnectionsRouteRouteWithChildren
  '/_authenticated/namespaces': typeof AuthenticatedNamespacesRouteRouteWithChildren
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRouteRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteRouteWithChildren
  '/_authenticated/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/_authenticated/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/namespaces/': typeof AuthenticatedNamespacesIndexRoute
  '/_authenticated/admin/groups/$groupId': typeof AuthenticatedAdminGroupsGroupIdRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/admin/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/connections'
    | '/namespaces'
    | '/admin/groups'
    | '/admin/users'
    | '/connections/$connectionId'
    | '/namespaces/$'
    | '/admin/'
    | '/connections/'
    | '/dashboard'
    | '/namespaces/'
    | '/admin/groups/$groupId'
    | '/admin/users/$userId'
    | '/admin/groups/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/connections/$connectionId'
    | '/namespaces/$'
    | '/admin'
    | '/connections'
    | '/dashboard'
    | '/namespaces'
    | '/admin/groups/$groupId'
    | '/admin/users/$userId'
    | '/admin/groups'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/connections'
    | '/_authenticated/namespaces'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/users'
    | '/_authenticated/connections/$connectionId'
    | '/_authenticated/namespaces/$'
    | '/_authenticated/admin/'
    | '/_authenticated/connections/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/namespaces/'
    | '/_authenticated/admin/groups/$groupId'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/admin/groups/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/namespaces': {
      id: '/_authenticated/namespaces'
      path: '/namespaces'
      fullPath: '/namespaces'
      preLoaderRoute: typeof AuthenticatedNamespacesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespaces/': {
      id: '/_authenticated/namespaces/'
      path: '/'
      fullPath: '/namespaces/'
      preLoaderRoute: typeof AuthenticatedNamespacesIndexRouteImport
      parentRoute: typeof AuthenticatedNamespacesRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections/': {
      id: '/_authenticated/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthenticatedConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedConnectionsRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/namespaces/$': {
      id: '/_authenticated/namespaces/$'
      path: '/$'
      fullPath: '/namespaces/$'
      preLoaderRoute: typeof AuthenticatedNamespacesSplatRouteImport
      parentRoute: typeof AuthenticatedNamespacesRouteRoute
    }
    '/_authenticated/connections/$connectionId': {
      id: '/_authenticated/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof AuthenticatedConnectionsConnectionIdRouteImport
      parentRoute: typeof AuthenticatedConnectionsRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRouteRoute
    }
    '/_authenticated/admin/groups/': {
      id: '/_authenticated/admin/groups/'
      path: '/'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AuthenticatedAdminGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminGroupsRouteRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRouteRoute
    }
    '/_authenticated/admin/groups/$groupId': {
      id: '/_authenticated/admin/groups/$groupId'
      path: '/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedAdminGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedAdminGroupsRouteRoute
    }
  }
}

interface AuthenticatedAdminGroupsRouteRouteChildren {
  AuthenticatedAdminGroupsGroupIdRoute: typeof AuthenticatedAdminGroupsGroupIdRoute
  AuthenticatedAdminGroupsIndexRoute: typeof AuthenticatedAdminGroupsIndexRoute
}

const AuthenticatedAdminGroupsRouteRouteChildren: AuthenticatedAdminGroupsRouteRouteChildren =
  {
    AuthenticatedAdminGroupsGroupIdRoute: AuthenticatedAdminGroupsGroupIdRoute,
    AuthenticatedAdminGroupsIndexRoute: AuthenticatedAdminGroupsIndexRoute,
  }

const AuthenticatedAdminGroupsRouteRouteWithChildren =
  AuthenticatedAdminGroupsRouteRoute._addFileChildren(
    AuthenticatedAdminGroupsRouteRouteChildren,
  )

interface AuthenticatedAdminUsersRouteRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminUsersRouteRouteChildren: AuthenticatedAdminUsersRouteRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminUsersRouteRouteWithChildren =
  AuthenticatedAdminUsersRouteRoute._addFileChildren(
    AuthenticatedAdminUsersRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminGroupsRouteRoute: typeof AuthenticatedAdminGroupsRouteRouteWithChildren
  AuthenticatedAdminUsersRouteRoute: typeof AuthenticatedAdminUsersRouteRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminGroupsRouteRoute:
      AuthenticatedAdminGroupsRouteRouteWithChildren,
    AuthenticatedAdminUsersRouteRoute:
      AuthenticatedAdminUsersRouteRouteWithChildren,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedConnectionsRouteRouteChildren {
  AuthenticatedConnectionsConnectionIdRoute: typeof AuthenticatedConnectionsConnectionIdRoute
  AuthenticatedConnectionsIndexRoute: typeof AuthenticatedConnectionsIndexRoute
}

const AuthenticatedConnectionsRouteRouteChildren: AuthenticatedConnectionsRouteRouteChildren =
  {
    AuthenticatedConnectionsConnectionIdRoute:
      AuthenticatedConnectionsConnectionIdRoute,
    AuthenticatedConnectionsIndexRoute: AuthenticatedConnectionsIndexRoute,
  }

const AuthenticatedConnectionsRouteRouteWithChildren =
  AuthenticatedConnectionsRouteRoute._addFileChildren(
    AuthenticatedConnectionsRouteRouteChildren,
  )

interface AuthenticatedNamespacesRouteRouteChildren {
  AuthenticatedNamespacesSplatRoute: typeof AuthenticatedNamespacesSplatRoute
  AuthenticatedNamespacesIndexRoute: typeof AuthenticatedNamespacesIndexRoute
}

const AuthenticatedNamespacesRouteRouteChildren: AuthenticatedNamespacesRouteRouteChildren =
  {
    AuthenticatedNamespacesSplatRoute: AuthenticatedNamespacesSplatRoute,
    AuthenticatedNamespacesIndexRoute: AuthenticatedNamespacesIndexRoute,
  }

const AuthenticatedNamespacesRouteRouteWithChildren =
  AuthenticatedNamespacesRouteRoute._addFileChildren(
    AuthenticatedNamespacesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedConnectionsRouteRoute: typeof AuthenticatedConnectionsRouteRouteWithChildren
  AuthenticatedNamespacesRouteRoute: typeof AuthenticatedNamespacesRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedConnectionsRouteRoute:
    AuthenticatedConnectionsRouteRouteWithChildren,
  AuthenticatedNamespacesRouteRoute:
    AuthenticatedNamespacesRouteRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
