/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSchemasRouteRouteImport } from './routes/_authenticated/schemas/route'
import { Route as AuthenticatedPermissionsRouteRouteImport } from './routes/_authenticated/permissions/route'
import { Route as AuthenticatedPeopleRouteRouteImport } from './routes/_authenticated/people/route'
import { Route as AuthenticatedNamespacesRouteRouteImport } from './routes/_authenticated/namespaces/route'
import { Route as AuthenticatedLoggingRouteRouteImport } from './routes/_authenticated/logging/route'
import { Route as AuthenticatedInterfacesRouteRouteImport } from './routes/_authenticated/interfaces/route'
import { Route as AuthenticatedDevicesRouteRouteImport } from './routes/_authenticated/devices/route'
import { Route as AuthenticatedConnectionsRouteRouteImport } from './routes/_authenticated/connections/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSchemasIndexRouteImport } from './routes/_authenticated/schemas/index'
import { Route as AuthenticatedPermissionsIndexRouteImport } from './routes/_authenticated/permissions/index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedConnectionsIndexRouteImport } from './routes/_authenticated/connections/index'
import { Route as AuthenticatedSettingsConfigNameRouteImport } from './routes/_authenticated/settings/$configName'
import { Route as AuthenticatedSchemasSchemaIdRouteImport } from './routes/_authenticated/schemas/$schemaId'
import { Route as AuthenticatedNamespacesSplatRouteImport } from './routes/_authenticated/namespaces/$'
import { Route as AuthenticatedConnectionsConnectionIdRouteImport } from './routes/_authenticated/connections/$connectionId'
import { Route as AuthenticatedPermissionsServerRouteRouteImport } from './routes/_authenticated/permissions/server/route'
import { Route as AuthenticatedPermissionsNamespaceRouteRouteImport } from './routes/_authenticated/permissions/namespace/route'
import { Route as AuthenticatedPeopleUsersRouteRouteImport } from './routes/_authenticated/people/users/route'
import { Route as AuthenticatedPeopleGroupsRouteRouteImport } from './routes/_authenticated/people/groups/route'
import { Route as AuthenticatedPermissionsServerIndexRouteImport } from './routes/_authenticated/permissions/server/index'
import { Route as AuthenticatedPeopleUsersIndexRouteImport } from './routes/_authenticated/people/users/index'
import { Route as AuthenticatedPeopleGroupsIndexRouteImport } from './routes/_authenticated/people/groups/index'
import { Route as AuthenticatedPermissionsNamespaceSplatRouteImport } from './routes/_authenticated/permissions/namespace/$'
import { Route as AuthenticatedPeopleUsersUserIdRouteImport } from './routes/_authenticated/people/users/$userId'
import { Route as AuthenticatedPeopleGroupsGroupIdRouteImport } from './routes/_authenticated/people/groups/$groupId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchemasRouteRoute =
  AuthenticatedSchemasRouteRouteImport.update({
    id: '/schemas',
    path: '/schemas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionsRouteRoute =
  AuthenticatedPermissionsRouteRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleRouteRoute =
  AuthenticatedPeopleRouteRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNamespacesRouteRoute =
  AuthenticatedNamespacesRouteRouteImport.update({
    id: '/namespaces',
    path: '/namespaces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoggingRouteRoute =
  AuthenticatedLoggingRouteRouteImport.update({
    id: '/logging',
    path: '/logging',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterfacesRouteRoute =
  AuthenticatedInterfacesRouteRouteImport.update({
    id: '/interfaces',
    path: '/interfaces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevicesRouteRoute =
  AuthenticatedDevicesRouteRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRouteRoute =
  AuthenticatedConnectionsRouteRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSchemasIndexRoute =
  AuthenticatedSchemasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchemasRouteRoute,
  } as any)
const AuthenticatedPermissionsIndexRoute =
  AuthenticatedPermissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPermissionsRouteRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsIndexRoute =
  AuthenticatedConnectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConnectionsRouteRoute,
  } as any)
const AuthenticatedSettingsConfigNameRoute =
  AuthenticatedSettingsConfigNameRouteImport.update({
    id: '/$configName',
    path: '/$configName',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSchemasSchemaIdRoute =
  AuthenticatedSchemasSchemaIdRouteImport.update({
    id: '/$schemaId',
    path: '/$schemaId',
    getParentRoute: () => AuthenticatedSchemasRouteRoute,
  } as any)
const AuthenticatedNamespacesSplatRoute =
  AuthenticatedNamespacesSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedNamespacesRouteRoute,
  } as any)
const AuthenticatedConnectionsConnectionIdRoute =
  AuthenticatedConnectionsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => AuthenticatedConnectionsRouteRoute,
  } as any)
const AuthenticatedPermissionsServerRouteRoute =
  AuthenticatedPermissionsServerRouteRouteImport.update({
    id: '/server',
    path: '/server',
    getParentRoute: () => AuthenticatedPermissionsRouteRoute,
  } as any)
const AuthenticatedPermissionsNamespaceRouteRoute =
  AuthenticatedPermissionsNamespaceRouteRouteImport.update({
    id: '/namespace',
    path: '/namespace',
    getParentRoute: () => AuthenticatedPermissionsRouteRoute,
  } as any)
const AuthenticatedPeopleUsersRouteRoute =
  AuthenticatedPeopleUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedPeopleRouteRoute,
  } as any)
const AuthenticatedPeopleGroupsRouteRoute =
  AuthenticatedPeopleGroupsRouteRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedPeopleRouteRoute,
  } as any)
const AuthenticatedPermissionsServerIndexRoute =
  AuthenticatedPermissionsServerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPermissionsServerRouteRoute,
  } as any)
const AuthenticatedPeopleUsersIndexRoute =
  AuthenticatedPeopleUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleUsersRouteRoute,
  } as any)
const AuthenticatedPeopleGroupsIndexRoute =
  AuthenticatedPeopleGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleGroupsRouteRoute,
  } as any)
const AuthenticatedPermissionsNamespaceSplatRoute =
  AuthenticatedPermissionsNamespaceSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedPermissionsNamespaceRouteRoute,
  } as any)
const AuthenticatedPeopleUsersUserIdRoute =
  AuthenticatedPeopleUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedPeopleUsersRouteRoute,
  } as any)
const AuthenticatedPeopleGroupsGroupIdRoute =
  AuthenticatedPeopleGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedPeopleGroupsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connections': typeof AuthenticatedConnectionsRouteRouteWithChildren
  '/devices': typeof AuthenticatedDevicesRouteRoute
  '/interfaces': typeof AuthenticatedInterfacesRouteRoute
  '/logging': typeof AuthenticatedLoggingRouteRoute
  '/namespaces': typeof AuthenticatedNamespacesRouteRouteWithChildren
  '/people': typeof AuthenticatedPeopleRouteRouteWithChildren
  '/permissions': typeof AuthenticatedPermissionsRouteRouteWithChildren
  '/schemas': typeof AuthenticatedSchemasRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/people/groups': typeof AuthenticatedPeopleGroupsRouteRouteWithChildren
  '/people/users': typeof AuthenticatedPeopleUsersRouteRouteWithChildren
  '/permissions/namespace': typeof AuthenticatedPermissionsNamespaceRouteRouteWithChildren
  '/permissions/server': typeof AuthenticatedPermissionsServerRouteRouteWithChildren
  '/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/schemas/$schemaId': typeof AuthenticatedSchemasSchemaIdRoute
  '/settings/$configName': typeof AuthenticatedSettingsConfigNameRoute
  '/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/schemas/': typeof AuthenticatedSchemasIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/people/groups/$groupId': typeof AuthenticatedPeopleGroupsGroupIdRoute
  '/people/users/$userId': typeof AuthenticatedPeopleUsersUserIdRoute
  '/permissions/namespace/$': typeof AuthenticatedPermissionsNamespaceSplatRoute
  '/people/groups/': typeof AuthenticatedPeopleGroupsIndexRoute
  '/people/users/': typeof AuthenticatedPeopleUsersIndexRoute
  '/permissions/server/': typeof AuthenticatedPermissionsServerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/devices': typeof AuthenticatedDevicesRouteRoute
  '/interfaces': typeof AuthenticatedInterfacesRouteRoute
  '/logging': typeof AuthenticatedLoggingRouteRoute
  '/namespaces': typeof AuthenticatedNamespacesRouteRouteWithChildren
  '/permissions/namespace': typeof AuthenticatedPermissionsNamespaceRouteRouteWithChildren
  '/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/schemas/$schemaId': typeof AuthenticatedSchemasSchemaIdRoute
  '/settings/$configName': typeof AuthenticatedSettingsConfigNameRoute
  '/connections': typeof AuthenticatedConnectionsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/permissions': typeof AuthenticatedPermissionsIndexRoute
  '/schemas': typeof AuthenticatedSchemasIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/people/groups/$groupId': typeof AuthenticatedPeopleGroupsGroupIdRoute
  '/people/users/$userId': typeof AuthenticatedPeopleUsersUserIdRoute
  '/permissions/namespace/$': typeof AuthenticatedPermissionsNamespaceSplatRoute
  '/people/groups': typeof AuthenticatedPeopleGroupsIndexRoute
  '/people/users': typeof AuthenticatedPeopleUsersIndexRoute
  '/permissions/server': typeof AuthenticatedPermissionsServerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRouteRouteWithChildren
  '/_authenticated/devices': typeof AuthenticatedDevicesRouteRoute
  '/_authenticated/interfaces': typeof AuthenticatedInterfacesRouteRoute
  '/_authenticated/logging': typeof AuthenticatedLoggingRouteRoute
  '/_authenticated/namespaces': typeof AuthenticatedNamespacesRouteRouteWithChildren
  '/_authenticated/people': typeof AuthenticatedPeopleRouteRouteWithChildren
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRouteRouteWithChildren
  '/_authenticated/schemas': typeof AuthenticatedSchemasRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/people/groups': typeof AuthenticatedPeopleGroupsRouteRouteWithChildren
  '/_authenticated/people/users': typeof AuthenticatedPeopleUsersRouteRouteWithChildren
  '/_authenticated/permissions/namespace': typeof AuthenticatedPermissionsNamespaceRouteRouteWithChildren
  '/_authenticated/permissions/server': typeof AuthenticatedPermissionsServerRouteRouteWithChildren
  '/_authenticated/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/_authenticated/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/_authenticated/schemas/$schemaId': typeof AuthenticatedSchemasSchemaIdRoute
  '/_authenticated/settings/$configName': typeof AuthenticatedSettingsConfigNameRoute
  '/_authenticated/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/permissions/': typeof AuthenticatedPermissionsIndexRoute
  '/_authenticated/schemas/': typeof AuthenticatedSchemasIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/people/groups/$groupId': typeof AuthenticatedPeopleGroupsGroupIdRoute
  '/_authenticated/people/users/$userId': typeof AuthenticatedPeopleUsersUserIdRoute
  '/_authenticated/permissions/namespace/$': typeof AuthenticatedPermissionsNamespaceSplatRoute
  '/_authenticated/people/groups/': typeof AuthenticatedPeopleGroupsIndexRoute
  '/_authenticated/people/users/': typeof AuthenticatedPeopleUsersIndexRoute
  '/_authenticated/permissions/server/': typeof AuthenticatedPermissionsServerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/connections'
    | '/devices'
    | '/interfaces'
    | '/logging'
    | '/namespaces'
    | '/people'
    | '/permissions'
    | '/schemas'
    | '/settings'
    | '/people/groups'
    | '/people/users'
    | '/permissions/namespace'
    | '/permissions/server'
    | '/connections/$connectionId'
    | '/namespaces/$'
    | '/schemas/$schemaId'
    | '/settings/$configName'
    | '/connections/'
    | '/dashboard/'
    | '/people/'
    | '/permissions/'
    | '/schemas/'
    | '/settings/'
    | '/people/groups/$groupId'
    | '/people/users/$userId'
    | '/permissions/namespace/$'
    | '/people/groups/'
    | '/people/users/'
    | '/permissions/server/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/devices'
    | '/interfaces'
    | '/logging'
    | '/namespaces'
    | '/permissions/namespace'
    | '/connections/$connectionId'
    | '/namespaces/$'
    | '/schemas/$schemaId'
    | '/settings/$configName'
    | '/connections'
    | '/dashboard'
    | '/people'
    | '/permissions'
    | '/schemas'
    | '/settings'
    | '/people/groups/$groupId'
    | '/people/users/$userId'
    | '/permissions/namespace/$'
    | '/people/groups'
    | '/people/users'
    | '/permissions/server'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/connections'
    | '/_authenticated/devices'
    | '/_authenticated/interfaces'
    | '/_authenticated/logging'
    | '/_authenticated/namespaces'
    | '/_authenticated/people'
    | '/_authenticated/permissions'
    | '/_authenticated/schemas'
    | '/_authenticated/settings'
    | '/_authenticated/people/groups'
    | '/_authenticated/people/users'
    | '/_authenticated/permissions/namespace'
    | '/_authenticated/permissions/server'
    | '/_authenticated/connections/$connectionId'
    | '/_authenticated/namespaces/$'
    | '/_authenticated/schemas/$schemaId'
    | '/_authenticated/settings/$configName'
    | '/_authenticated/connections/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/people/'
    | '/_authenticated/permissions/'
    | '/_authenticated/schemas/'
    | '/_authenticated/settings/'
    | '/_authenticated/people/groups/$groupId'
    | '/_authenticated/people/users/$userId'
    | '/_authenticated/permissions/namespace/$'
    | '/_authenticated/people/groups/'
    | '/_authenticated/people/users/'
    | '/_authenticated/permissions/server/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemas': {
      id: '/_authenticated/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof AuthenticatedSchemasRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespaces': {
      id: '/_authenticated/namespaces'
      path: '/namespaces'
      fullPath: '/namespaces'
      preLoaderRoute: typeof AuthenticatedNamespacesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logging': {
      id: '/_authenticated/logging'
      path: '/logging'
      fullPath: '/logging'
      preLoaderRoute: typeof AuthenticatedLoggingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interfaces': {
      id: '/_authenticated/interfaces'
      path: '/interfaces'
      fullPath: '/interfaces'
      preLoaderRoute: typeof AuthenticatedInterfacesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/schemas/': {
      id: '/_authenticated/schemas/'
      path: '/'
      fullPath: '/schemas/'
      preLoaderRoute: typeof AuthenticatedSchemasIndexRouteImport
      parentRoute: typeof AuthenticatedSchemasRouteRoute
    }
    '/_authenticated/permissions/': {
      id: '/_authenticated/permissions/'
      path: '/'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AuthenticatedPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedPermissionsRouteRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections/': {
      id: '/_authenticated/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthenticatedConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedConnectionsRouteRoute
    }
    '/_authenticated/settings/$configName': {
      id: '/_authenticated/settings/$configName'
      path: '/$configName'
      fullPath: '/settings/$configName'
      preLoaderRoute: typeof AuthenticatedSettingsConfigNameRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/schemas/$schemaId': {
      id: '/_authenticated/schemas/$schemaId'
      path: '/$schemaId'
      fullPath: '/schemas/$schemaId'
      preLoaderRoute: typeof AuthenticatedSchemasSchemaIdRouteImport
      parentRoute: typeof AuthenticatedSchemasRouteRoute
    }
    '/_authenticated/namespaces/$': {
      id: '/_authenticated/namespaces/$'
      path: '/$'
      fullPath: '/namespaces/$'
      preLoaderRoute: typeof AuthenticatedNamespacesSplatRouteImport
      parentRoute: typeof AuthenticatedNamespacesRouteRoute
    }
    '/_authenticated/connections/$connectionId': {
      id: '/_authenticated/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof AuthenticatedConnectionsConnectionIdRouteImport
      parentRoute: typeof AuthenticatedConnectionsRouteRoute
    }
    '/_authenticated/permissions/server': {
      id: '/_authenticated/permissions/server'
      path: '/server'
      fullPath: '/permissions/server'
      preLoaderRoute: typeof AuthenticatedPermissionsServerRouteRouteImport
      parentRoute: typeof AuthenticatedPermissionsRouteRoute
    }
    '/_authenticated/permissions/namespace': {
      id: '/_authenticated/permissions/namespace'
      path: '/namespace'
      fullPath: '/permissions/namespace'
      preLoaderRoute: typeof AuthenticatedPermissionsNamespaceRouteRouteImport
      parentRoute: typeof AuthenticatedPermissionsRouteRoute
    }
    '/_authenticated/people/users': {
      id: '/_authenticated/people/users'
      path: '/users'
      fullPath: '/people/users'
      preLoaderRoute: typeof AuthenticatedPeopleUsersRouteRouteImport
      parentRoute: typeof AuthenticatedPeopleRouteRoute
    }
    '/_authenticated/people/groups': {
      id: '/_authenticated/people/groups'
      path: '/groups'
      fullPath: '/people/groups'
      preLoaderRoute: typeof AuthenticatedPeopleGroupsRouteRouteImport
      parentRoute: typeof AuthenticatedPeopleRouteRoute
    }
    '/_authenticated/permissions/server/': {
      id: '/_authenticated/permissions/server/'
      path: '/'
      fullPath: '/permissions/server/'
      preLoaderRoute: typeof AuthenticatedPermissionsServerIndexRouteImport
      parentRoute: typeof AuthenticatedPermissionsServerRouteRoute
    }
    '/_authenticated/people/users/': {
      id: '/_authenticated/people/users/'
      path: '/'
      fullPath: '/people/users/'
      preLoaderRoute: typeof AuthenticatedPeopleUsersIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleUsersRouteRoute
    }
    '/_authenticated/people/groups/': {
      id: '/_authenticated/people/groups/'
      path: '/'
      fullPath: '/people/groups/'
      preLoaderRoute: typeof AuthenticatedPeopleGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleGroupsRouteRoute
    }
    '/_authenticated/permissions/namespace/$': {
      id: '/_authenticated/permissions/namespace/$'
      path: '/$'
      fullPath: '/permissions/namespace/$'
      preLoaderRoute: typeof AuthenticatedPermissionsNamespaceSplatRouteImport
      parentRoute: typeof AuthenticatedPermissionsNamespaceRouteRoute
    }
    '/_authenticated/people/users/$userId': {
      id: '/_authenticated/people/users/$userId'
      path: '/$userId'
      fullPath: '/people/users/$userId'
      preLoaderRoute: typeof AuthenticatedPeopleUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedPeopleUsersRouteRoute
    }
    '/_authenticated/people/groups/$groupId': {
      id: '/_authenticated/people/groups/$groupId'
      path: '/$groupId'
      fullPath: '/people/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedPeopleGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedPeopleGroupsRouteRoute
    }
  }
}

interface AuthenticatedConnectionsRouteRouteChildren {
  AuthenticatedConnectionsConnectionIdRoute: typeof AuthenticatedConnectionsConnectionIdRoute
  AuthenticatedConnectionsIndexRoute: typeof AuthenticatedConnectionsIndexRoute
}

const AuthenticatedConnectionsRouteRouteChildren: AuthenticatedConnectionsRouteRouteChildren =
  {
    AuthenticatedConnectionsConnectionIdRoute:
      AuthenticatedConnectionsConnectionIdRoute,
    AuthenticatedConnectionsIndexRoute: AuthenticatedConnectionsIndexRoute,
  }

const AuthenticatedConnectionsRouteRouteWithChildren =
  AuthenticatedConnectionsRouteRoute._addFileChildren(
    AuthenticatedConnectionsRouteRouteChildren,
  )

interface AuthenticatedNamespacesRouteRouteChildren {
  AuthenticatedNamespacesSplatRoute: typeof AuthenticatedNamespacesSplatRoute
}

const AuthenticatedNamespacesRouteRouteChildren: AuthenticatedNamespacesRouteRouteChildren =
  {
    AuthenticatedNamespacesSplatRoute: AuthenticatedNamespacesSplatRoute,
  }

const AuthenticatedNamespacesRouteRouteWithChildren =
  AuthenticatedNamespacesRouteRoute._addFileChildren(
    AuthenticatedNamespacesRouteRouteChildren,
  )

interface AuthenticatedPeopleGroupsRouteRouteChildren {
  AuthenticatedPeopleGroupsGroupIdRoute: typeof AuthenticatedPeopleGroupsGroupIdRoute
  AuthenticatedPeopleGroupsIndexRoute: typeof AuthenticatedPeopleGroupsIndexRoute
}

const AuthenticatedPeopleGroupsRouteRouteChildren: AuthenticatedPeopleGroupsRouteRouteChildren =
  {
    AuthenticatedPeopleGroupsGroupIdRoute:
      AuthenticatedPeopleGroupsGroupIdRoute,
    AuthenticatedPeopleGroupsIndexRoute: AuthenticatedPeopleGroupsIndexRoute,
  }

const AuthenticatedPeopleGroupsRouteRouteWithChildren =
  AuthenticatedPeopleGroupsRouteRoute._addFileChildren(
    AuthenticatedPeopleGroupsRouteRouteChildren,
  )

interface AuthenticatedPeopleUsersRouteRouteChildren {
  AuthenticatedPeopleUsersUserIdRoute: typeof AuthenticatedPeopleUsersUserIdRoute
  AuthenticatedPeopleUsersIndexRoute: typeof AuthenticatedPeopleUsersIndexRoute
}

const AuthenticatedPeopleUsersRouteRouteChildren: AuthenticatedPeopleUsersRouteRouteChildren =
  {
    AuthenticatedPeopleUsersUserIdRoute: AuthenticatedPeopleUsersUserIdRoute,
    AuthenticatedPeopleUsersIndexRoute: AuthenticatedPeopleUsersIndexRoute,
  }

const AuthenticatedPeopleUsersRouteRouteWithChildren =
  AuthenticatedPeopleUsersRouteRoute._addFileChildren(
    AuthenticatedPeopleUsersRouteRouteChildren,
  )

interface AuthenticatedPeopleRouteRouteChildren {
  AuthenticatedPeopleGroupsRouteRoute: typeof AuthenticatedPeopleGroupsRouteRouteWithChildren
  AuthenticatedPeopleUsersRouteRoute: typeof AuthenticatedPeopleUsersRouteRouteWithChildren
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedPeopleRouteRouteChildren: AuthenticatedPeopleRouteRouteChildren =
  {
    AuthenticatedPeopleGroupsRouteRoute:
      AuthenticatedPeopleGroupsRouteRouteWithChildren,
    AuthenticatedPeopleUsersRouteRoute:
      AuthenticatedPeopleUsersRouteRouteWithChildren,
    AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  }

const AuthenticatedPeopleRouteRouteWithChildren =
  AuthenticatedPeopleRouteRoute._addFileChildren(
    AuthenticatedPeopleRouteRouteChildren,
  )

interface AuthenticatedPermissionsNamespaceRouteRouteChildren {
  AuthenticatedPermissionsNamespaceSplatRoute: typeof AuthenticatedPermissionsNamespaceSplatRoute
}

const AuthenticatedPermissionsNamespaceRouteRouteChildren: AuthenticatedPermissionsNamespaceRouteRouteChildren =
  {
    AuthenticatedPermissionsNamespaceSplatRoute:
      AuthenticatedPermissionsNamespaceSplatRoute,
  }

const AuthenticatedPermissionsNamespaceRouteRouteWithChildren =
  AuthenticatedPermissionsNamespaceRouteRoute._addFileChildren(
    AuthenticatedPermissionsNamespaceRouteRouteChildren,
  )

interface AuthenticatedPermissionsServerRouteRouteChildren {
  AuthenticatedPermissionsServerIndexRoute: typeof AuthenticatedPermissionsServerIndexRoute
}

const AuthenticatedPermissionsServerRouteRouteChildren: AuthenticatedPermissionsServerRouteRouteChildren =
  {
    AuthenticatedPermissionsServerIndexRoute:
      AuthenticatedPermissionsServerIndexRoute,
  }

const AuthenticatedPermissionsServerRouteRouteWithChildren =
  AuthenticatedPermissionsServerRouteRoute._addFileChildren(
    AuthenticatedPermissionsServerRouteRouteChildren,
  )

interface AuthenticatedPermissionsRouteRouteChildren {
  AuthenticatedPermissionsNamespaceRouteRoute: typeof AuthenticatedPermissionsNamespaceRouteRouteWithChildren
  AuthenticatedPermissionsServerRouteRoute: typeof AuthenticatedPermissionsServerRouteRouteWithChildren
  AuthenticatedPermissionsIndexRoute: typeof AuthenticatedPermissionsIndexRoute
}

const AuthenticatedPermissionsRouteRouteChildren: AuthenticatedPermissionsRouteRouteChildren =
  {
    AuthenticatedPermissionsNamespaceRouteRoute:
      AuthenticatedPermissionsNamespaceRouteRouteWithChildren,
    AuthenticatedPermissionsServerRouteRoute:
      AuthenticatedPermissionsServerRouteRouteWithChildren,
    AuthenticatedPermissionsIndexRoute: AuthenticatedPermissionsIndexRoute,
  }

const AuthenticatedPermissionsRouteRouteWithChildren =
  AuthenticatedPermissionsRouteRoute._addFileChildren(
    AuthenticatedPermissionsRouteRouteChildren,
  )

interface AuthenticatedSchemasRouteRouteChildren {
  AuthenticatedSchemasSchemaIdRoute: typeof AuthenticatedSchemasSchemaIdRoute
  AuthenticatedSchemasIndexRoute: typeof AuthenticatedSchemasIndexRoute
}

const AuthenticatedSchemasRouteRouteChildren: AuthenticatedSchemasRouteRouteChildren =
  {
    AuthenticatedSchemasSchemaIdRoute: AuthenticatedSchemasSchemaIdRoute,
    AuthenticatedSchemasIndexRoute: AuthenticatedSchemasIndexRoute,
  }

const AuthenticatedSchemasRouteRouteWithChildren =
  AuthenticatedSchemasRouteRoute._addFileChildren(
    AuthenticatedSchemasRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsConfigNameRoute: typeof AuthenticatedSettingsConfigNameRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsConfigNameRoute: AuthenticatedSettingsConfigNameRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectionsRouteRoute: typeof AuthenticatedConnectionsRouteRouteWithChildren
  AuthenticatedDevicesRouteRoute: typeof AuthenticatedDevicesRouteRoute
  AuthenticatedInterfacesRouteRoute: typeof AuthenticatedInterfacesRouteRoute
  AuthenticatedLoggingRouteRoute: typeof AuthenticatedLoggingRouteRoute
  AuthenticatedNamespacesRouteRoute: typeof AuthenticatedNamespacesRouteRouteWithChildren
  AuthenticatedPeopleRouteRoute: typeof AuthenticatedPeopleRouteRouteWithChildren
  AuthenticatedPermissionsRouteRoute: typeof AuthenticatedPermissionsRouteRouteWithChildren
  AuthenticatedSchemasRouteRoute: typeof AuthenticatedSchemasRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectionsRouteRoute:
    AuthenticatedConnectionsRouteRouteWithChildren,
  AuthenticatedDevicesRouteRoute: AuthenticatedDevicesRouteRoute,
  AuthenticatedInterfacesRouteRoute: AuthenticatedInterfacesRouteRoute,
  AuthenticatedLoggingRouteRoute: AuthenticatedLoggingRouteRoute,
  AuthenticatedNamespacesRouteRoute:
    AuthenticatedNamespacesRouteRouteWithChildren,
  AuthenticatedPeopleRouteRoute: AuthenticatedPeopleRouteRouteWithChildren,
  AuthenticatedPermissionsRouteRoute:
    AuthenticatedPermissionsRouteRouteWithChildren,
  AuthenticatedSchemasRouteRoute: AuthenticatedSchemasRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
