/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSchemasRouteRouteImport } from './routes/_authenticated/schemas/route'
import { Route as AuthenticatedPeopleRouteRouteImport } from './routes/_authenticated/people/route'
import { Route as AuthenticatedNamespacesRouteRouteImport } from './routes/_authenticated/namespaces/route'
import { Route as AuthenticatedConnectionsRouteRouteImport } from './routes/_authenticated/connections/route'
import { Route as AuthenticatedSchemasIndexRouteImport } from './routes/_authenticated/schemas/index'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedConnectionsIndexRouteImport } from './routes/_authenticated/connections/index'
import { Route as AuthenticatedSchemasSchemaIdRouteImport } from './routes/_authenticated/schemas/$schemaId'
import { Route as AuthenticatedNamespacesSplatRouteImport } from './routes/_authenticated/namespaces/$'
import { Route as AuthenticatedConnectionsConnectionIdRouteImport } from './routes/_authenticated/connections/$connectionId'
import { Route as AuthenticatedPeopleUsersRouteRouteImport } from './routes/_authenticated/people/users/route'
import { Route as AuthenticatedPeopleGroupsRouteRouteImport } from './routes/_authenticated/people/groups/route'
import { Route as AuthenticatedPeopleUsersIndexRouteImport } from './routes/_authenticated/people/users/index'
import { Route as AuthenticatedPeopleGroupsIndexRouteImport } from './routes/_authenticated/people/groups/index'
import { Route as AuthenticatedPeopleUsersUserIdRouteImport } from './routes/_authenticated/people/users/$userId'
import { Route as AuthenticatedPeopleGroupsGroupIdRouteImport } from './routes/_authenticated/people/groups/$groupId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchemasRouteRoute =
  AuthenticatedSchemasRouteRouteImport.update({
    id: '/schemas',
    path: '/schemas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleRouteRoute =
  AuthenticatedPeopleRouteRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNamespacesRouteRoute =
  AuthenticatedNamespacesRouteRouteImport.update({
    id: '/namespaces',
    path: '/namespaces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRouteRoute =
  AuthenticatedConnectionsRouteRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchemasIndexRoute =
  AuthenticatedSchemasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchemasRouteRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsIndexRoute =
  AuthenticatedConnectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConnectionsRouteRoute,
  } as any)
const AuthenticatedSchemasSchemaIdRoute =
  AuthenticatedSchemasSchemaIdRouteImport.update({
    id: '/$schemaId',
    path: '/$schemaId',
    getParentRoute: () => AuthenticatedSchemasRouteRoute,
  } as any)
const AuthenticatedNamespacesSplatRoute =
  AuthenticatedNamespacesSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedNamespacesRouteRoute,
  } as any)
const AuthenticatedConnectionsConnectionIdRoute =
  AuthenticatedConnectionsConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => AuthenticatedConnectionsRouteRoute,
  } as any)
const AuthenticatedPeopleUsersRouteRoute =
  AuthenticatedPeopleUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedPeopleRouteRoute,
  } as any)
const AuthenticatedPeopleGroupsRouteRoute =
  AuthenticatedPeopleGroupsRouteRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedPeopleRouteRoute,
  } as any)
const AuthenticatedPeopleUsersIndexRoute =
  AuthenticatedPeopleUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleUsersRouteRoute,
  } as any)
const AuthenticatedPeopleGroupsIndexRoute =
  AuthenticatedPeopleGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleGroupsRouteRoute,
  } as any)
const AuthenticatedPeopleUsersUserIdRoute =
  AuthenticatedPeopleUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedPeopleUsersRouteRoute,
  } as any)
const AuthenticatedPeopleGroupsGroupIdRoute =
  AuthenticatedPeopleGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedPeopleGroupsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connections': typeof AuthenticatedConnectionsRouteRouteWithChildren
  '/namespaces': typeof AuthenticatedNamespacesRouteRouteWithChildren
  '/people': typeof AuthenticatedPeopleRouteRouteWithChildren
  '/schemas': typeof AuthenticatedSchemasRouteRouteWithChildren
  '/people/groups': typeof AuthenticatedPeopleGroupsRouteRouteWithChildren
  '/people/users': typeof AuthenticatedPeopleUsersRouteRouteWithChildren
  '/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/schemas/$schemaId': typeof AuthenticatedSchemasSchemaIdRoute
  '/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/schemas/': typeof AuthenticatedSchemasIndexRoute
  '/people/groups/$groupId': typeof AuthenticatedPeopleGroupsGroupIdRoute
  '/people/users/$userId': typeof AuthenticatedPeopleUsersUserIdRoute
  '/people/groups/': typeof AuthenticatedPeopleGroupsIndexRoute
  '/people/users/': typeof AuthenticatedPeopleUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/namespaces': typeof AuthenticatedNamespacesRouteRouteWithChildren
  '/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/schemas/$schemaId': typeof AuthenticatedSchemasSchemaIdRoute
  '/connections': typeof AuthenticatedConnectionsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/schemas': typeof AuthenticatedSchemasIndexRoute
  '/people/groups/$groupId': typeof AuthenticatedPeopleGroupsGroupIdRoute
  '/people/users/$userId': typeof AuthenticatedPeopleUsersUserIdRoute
  '/people/groups': typeof AuthenticatedPeopleGroupsIndexRoute
  '/people/users': typeof AuthenticatedPeopleUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRouteRouteWithChildren
  '/_authenticated/namespaces': typeof AuthenticatedNamespacesRouteRouteWithChildren
  '/_authenticated/people': typeof AuthenticatedPeopleRouteRouteWithChildren
  '/_authenticated/schemas': typeof AuthenticatedSchemasRouteRouteWithChildren
  '/_authenticated/people/groups': typeof AuthenticatedPeopleGroupsRouteRouteWithChildren
  '/_authenticated/people/users': typeof AuthenticatedPeopleUsersRouteRouteWithChildren
  '/_authenticated/connections/$connectionId': typeof AuthenticatedConnectionsConnectionIdRoute
  '/_authenticated/namespaces/$': typeof AuthenticatedNamespacesSplatRoute
  '/_authenticated/schemas/$schemaId': typeof AuthenticatedSchemasSchemaIdRoute
  '/_authenticated/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/schemas/': typeof AuthenticatedSchemasIndexRoute
  '/_authenticated/people/groups/$groupId': typeof AuthenticatedPeopleGroupsGroupIdRoute
  '/_authenticated/people/users/$userId': typeof AuthenticatedPeopleUsersUserIdRoute
  '/_authenticated/people/groups/': typeof AuthenticatedPeopleGroupsIndexRoute
  '/_authenticated/people/users/': typeof AuthenticatedPeopleUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/connections'
    | '/namespaces'
    | '/people'
    | '/schemas'
    | '/people/groups'
    | '/people/users'
    | '/connections/$connectionId'
    | '/namespaces/$'
    | '/schemas/$schemaId'
    | '/connections/'
    | '/dashboard/'
    | '/people/'
    | '/schemas/'
    | '/people/groups/$groupId'
    | '/people/users/$userId'
    | '/people/groups/'
    | '/people/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/namespaces'
    | '/connections/$connectionId'
    | '/namespaces/$'
    | '/schemas/$schemaId'
    | '/connections'
    | '/dashboard'
    | '/people'
    | '/schemas'
    | '/people/groups/$groupId'
    | '/people/users/$userId'
    | '/people/groups'
    | '/people/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/connections'
    | '/_authenticated/namespaces'
    | '/_authenticated/people'
    | '/_authenticated/schemas'
    | '/_authenticated/people/groups'
    | '/_authenticated/people/users'
    | '/_authenticated/connections/$connectionId'
    | '/_authenticated/namespaces/$'
    | '/_authenticated/schemas/$schemaId'
    | '/_authenticated/connections/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/people/'
    | '/_authenticated/schemas/'
    | '/_authenticated/people/groups/$groupId'
    | '/_authenticated/people/users/$userId'
    | '/_authenticated/people/groups/'
    | '/_authenticated/people/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schemas': {
      id: '/_authenticated/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof AuthenticatedSchemasRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/namespaces': {
      id: '/_authenticated/namespaces'
      path: '/namespaces'
      fullPath: '/namespaces'
      preLoaderRoute: typeof AuthenticatedNamespacesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemas/': {
      id: '/_authenticated/schemas/'
      path: '/'
      fullPath: '/schemas/'
      preLoaderRoute: typeof AuthenticatedSchemasIndexRouteImport
      parentRoute: typeof AuthenticatedSchemasRouteRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections/': {
      id: '/_authenticated/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthenticatedConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedConnectionsRouteRoute
    }
    '/_authenticated/schemas/$schemaId': {
      id: '/_authenticated/schemas/$schemaId'
      path: '/$schemaId'
      fullPath: '/schemas/$schemaId'
      preLoaderRoute: typeof AuthenticatedSchemasSchemaIdRouteImport
      parentRoute: typeof AuthenticatedSchemasRouteRoute
    }
    '/_authenticated/namespaces/$': {
      id: '/_authenticated/namespaces/$'
      path: '/$'
      fullPath: '/namespaces/$'
      preLoaderRoute: typeof AuthenticatedNamespacesSplatRouteImport
      parentRoute: typeof AuthenticatedNamespacesRouteRoute
    }
    '/_authenticated/connections/$connectionId': {
      id: '/_authenticated/connections/$connectionId'
      path: '/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof AuthenticatedConnectionsConnectionIdRouteImport
      parentRoute: typeof AuthenticatedConnectionsRouteRoute
    }
    '/_authenticated/people/users': {
      id: '/_authenticated/people/users'
      path: '/users'
      fullPath: '/people/users'
      preLoaderRoute: typeof AuthenticatedPeopleUsersRouteRouteImport
      parentRoute: typeof AuthenticatedPeopleRouteRoute
    }
    '/_authenticated/people/groups': {
      id: '/_authenticated/people/groups'
      path: '/groups'
      fullPath: '/people/groups'
      preLoaderRoute: typeof AuthenticatedPeopleGroupsRouteRouteImport
      parentRoute: typeof AuthenticatedPeopleRouteRoute
    }
    '/_authenticated/people/users/': {
      id: '/_authenticated/people/users/'
      path: '/'
      fullPath: '/people/users/'
      preLoaderRoute: typeof AuthenticatedPeopleUsersIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleUsersRouteRoute
    }
    '/_authenticated/people/groups/': {
      id: '/_authenticated/people/groups/'
      path: '/'
      fullPath: '/people/groups/'
      preLoaderRoute: typeof AuthenticatedPeopleGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleGroupsRouteRoute
    }
    '/_authenticated/people/users/$userId': {
      id: '/_authenticated/people/users/$userId'
      path: '/$userId'
      fullPath: '/people/users/$userId'
      preLoaderRoute: typeof AuthenticatedPeopleUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedPeopleUsersRouteRoute
    }
    '/_authenticated/people/groups/$groupId': {
      id: '/_authenticated/people/groups/$groupId'
      path: '/$groupId'
      fullPath: '/people/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedPeopleGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedPeopleGroupsRouteRoute
    }
  }
}

interface AuthenticatedConnectionsRouteRouteChildren {
  AuthenticatedConnectionsConnectionIdRoute: typeof AuthenticatedConnectionsConnectionIdRoute
  AuthenticatedConnectionsIndexRoute: typeof AuthenticatedConnectionsIndexRoute
}

const AuthenticatedConnectionsRouteRouteChildren: AuthenticatedConnectionsRouteRouteChildren =
  {
    AuthenticatedConnectionsConnectionIdRoute:
      AuthenticatedConnectionsConnectionIdRoute,
    AuthenticatedConnectionsIndexRoute: AuthenticatedConnectionsIndexRoute,
  }

const AuthenticatedConnectionsRouteRouteWithChildren =
  AuthenticatedConnectionsRouteRoute._addFileChildren(
    AuthenticatedConnectionsRouteRouteChildren,
  )

interface AuthenticatedNamespacesRouteRouteChildren {
  AuthenticatedNamespacesSplatRoute: typeof AuthenticatedNamespacesSplatRoute
}

const AuthenticatedNamespacesRouteRouteChildren: AuthenticatedNamespacesRouteRouteChildren =
  {
    AuthenticatedNamespacesSplatRoute: AuthenticatedNamespacesSplatRoute,
  }

const AuthenticatedNamespacesRouteRouteWithChildren =
  AuthenticatedNamespacesRouteRoute._addFileChildren(
    AuthenticatedNamespacesRouteRouteChildren,
  )

interface AuthenticatedPeopleGroupsRouteRouteChildren {
  AuthenticatedPeopleGroupsGroupIdRoute: typeof AuthenticatedPeopleGroupsGroupIdRoute
  AuthenticatedPeopleGroupsIndexRoute: typeof AuthenticatedPeopleGroupsIndexRoute
}

const AuthenticatedPeopleGroupsRouteRouteChildren: AuthenticatedPeopleGroupsRouteRouteChildren =
  {
    AuthenticatedPeopleGroupsGroupIdRoute:
      AuthenticatedPeopleGroupsGroupIdRoute,
    AuthenticatedPeopleGroupsIndexRoute: AuthenticatedPeopleGroupsIndexRoute,
  }

const AuthenticatedPeopleGroupsRouteRouteWithChildren =
  AuthenticatedPeopleGroupsRouteRoute._addFileChildren(
    AuthenticatedPeopleGroupsRouteRouteChildren,
  )

interface AuthenticatedPeopleUsersRouteRouteChildren {
  AuthenticatedPeopleUsersUserIdRoute: typeof AuthenticatedPeopleUsersUserIdRoute
  AuthenticatedPeopleUsersIndexRoute: typeof AuthenticatedPeopleUsersIndexRoute
}

const AuthenticatedPeopleUsersRouteRouteChildren: AuthenticatedPeopleUsersRouteRouteChildren =
  {
    AuthenticatedPeopleUsersUserIdRoute: AuthenticatedPeopleUsersUserIdRoute,
    AuthenticatedPeopleUsersIndexRoute: AuthenticatedPeopleUsersIndexRoute,
  }

const AuthenticatedPeopleUsersRouteRouteWithChildren =
  AuthenticatedPeopleUsersRouteRoute._addFileChildren(
    AuthenticatedPeopleUsersRouteRouteChildren,
  )

interface AuthenticatedPeopleRouteRouteChildren {
  AuthenticatedPeopleGroupsRouteRoute: typeof AuthenticatedPeopleGroupsRouteRouteWithChildren
  AuthenticatedPeopleUsersRouteRoute: typeof AuthenticatedPeopleUsersRouteRouteWithChildren
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedPeopleRouteRouteChildren: AuthenticatedPeopleRouteRouteChildren =
  {
    AuthenticatedPeopleGroupsRouteRoute:
      AuthenticatedPeopleGroupsRouteRouteWithChildren,
    AuthenticatedPeopleUsersRouteRoute:
      AuthenticatedPeopleUsersRouteRouteWithChildren,
    AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  }

const AuthenticatedPeopleRouteRouteWithChildren =
  AuthenticatedPeopleRouteRoute._addFileChildren(
    AuthenticatedPeopleRouteRouteChildren,
  )

interface AuthenticatedSchemasRouteRouteChildren {
  AuthenticatedSchemasSchemaIdRoute: typeof AuthenticatedSchemasSchemaIdRoute
  AuthenticatedSchemasIndexRoute: typeof AuthenticatedSchemasIndexRoute
}

const AuthenticatedSchemasRouteRouteChildren: AuthenticatedSchemasRouteRouteChildren =
  {
    AuthenticatedSchemasSchemaIdRoute: AuthenticatedSchemasSchemaIdRoute,
    AuthenticatedSchemasIndexRoute: AuthenticatedSchemasIndexRoute,
  }

const AuthenticatedSchemasRouteRouteWithChildren =
  AuthenticatedSchemasRouteRoute._addFileChildren(
    AuthenticatedSchemasRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectionsRouteRoute: typeof AuthenticatedConnectionsRouteRouteWithChildren
  AuthenticatedNamespacesRouteRoute: typeof AuthenticatedNamespacesRouteRouteWithChildren
  AuthenticatedPeopleRouteRoute: typeof AuthenticatedPeopleRouteRouteWithChildren
  AuthenticatedSchemasRouteRoute: typeof AuthenticatedSchemasRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectionsRouteRoute:
    AuthenticatedConnectionsRouteRouteWithChildren,
  AuthenticatedNamespacesRouteRoute:
    AuthenticatedNamespacesRouteRouteWithChildren,
  AuthenticatedPeopleRouteRoute: AuthenticatedPeopleRouteRouteWithChildren,
  AuthenticatedSchemasRouteRoute: AuthenticatedSchemasRouteRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
